// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// run_adaptive_permutation_test
List run_adaptive_permutation_test(List precomp_list, IntegerVector x, int side_code, int h, double alpha, int max_iterations, std::string test_stat_str);
RcppExport SEXP _robustDESeq_run_adaptive_permutation_test(SEXP precomp_listSEXP, SEXP xSEXP, SEXP side_codeSEXP, SEXP hSEXP, SEXP alphaSEXP, SEXP max_iterationsSEXP, SEXP test_stat_strSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type precomp_list(precomp_listSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type side_code(side_codeSEXP);
    Rcpp::traits::input_parameter< int >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type max_iterations(max_iterationsSEXP);
    Rcpp::traits::input_parameter< std::string >::type test_stat_str(test_stat_strSEXP);
    rcpp_result_gen = Rcpp::wrap(run_adaptive_permutation_test(precomp_list, x, side_code, h, alpha, max_iterations, test_stat_str));
    return rcpp_result_gen;
END_RCPP
}
// compute_score_stat_benchmark
NumericVector compute_score_stat_benchmark(const List& precomp, int s, const List& trt_idxs_list);
RcppExport SEXP _robustDESeq_compute_score_stat_benchmark(SEXP precompSEXP, SEXP sSEXP, SEXP trt_idxs_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type precomp(precompSEXP);
    Rcpp::traits::input_parameter< int >::type s(sSEXP);
    Rcpp::traits::input_parameter< const List& >::type trt_idxs_list(trt_idxs_listSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_score_stat_benchmark(precomp, s, trt_idxs_list));
    return rcpp_result_gen;
END_RCPP
}
// run_permutation_test
std::vector<double> run_permutation_test(List precomp_list, IntegerVector x, int side_code, int B, std::string test_stat_str);
RcppExport SEXP _robustDESeq_run_permutation_test(SEXP precomp_listSEXP, SEXP xSEXP, SEXP side_codeSEXP, SEXP BSEXP, SEXP test_stat_strSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type precomp_list(precomp_listSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type side_code(side_codeSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< std::string >::type test_stat_str(test_stat_strSEXP);
    rcpp_result_gen = Rcpp::wrap(run_permutation_test(precomp_list, x, side_code, B, test_stat_str));
    return rcpp_result_gen;
END_RCPP
}
// generate_wor_sample_test
std::vector<std::vector<int>> generate_wor_sample_test(int n, int n_trt, int n_samples);
RcppExport SEXP _robustDESeq_generate_wor_sample_test(SEXP nSEXP, SEXP n_trtSEXP, SEXP n_samplesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type n_trt(n_trtSEXP);
    Rcpp::traits::input_parameter< int >::type n_samples(n_samplesSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_wor_sample_test(n, n_trt, n_samples));
    return rcpp_result_gen;
END_RCPP
}
// compute_score_stat
double compute_score_stat(List precomp, const std::vector<int>& trt_idxs, int n_trt);
RcppExport SEXP _robustDESeq_compute_score_stat(SEXP precompSEXP, SEXP trt_idxsSEXP, SEXP n_trtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type precomp(precompSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type trt_idxs(trt_idxsSEXP);
    Rcpp::traits::input_parameter< int >::type n_trt(n_trtSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_score_stat(precomp, trt_idxs, n_trt));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_robustDESeq_run_adaptive_permutation_test", (DL_FUNC) &_robustDESeq_run_adaptive_permutation_test, 7},
    {"_robustDESeq_compute_score_stat_benchmark", (DL_FUNC) &_robustDESeq_compute_score_stat_benchmark, 3},
    {"_robustDESeq_run_permutation_test", (DL_FUNC) &_robustDESeq_run_permutation_test, 5},
    {"_robustDESeq_generate_wor_sample_test", (DL_FUNC) &_robustDESeq_generate_wor_sample_test, 3},
    {"_robustDESeq_compute_score_stat", (DL_FUNC) &_robustDESeq_compute_score_stat, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_robustDESeq(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
