# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_adaptive_permutation_test <- function(precomp_list, x, h, alpha, test_stat_str) {
    .Call(`_robustDESeq_run_adaptive_permutation_test`, precomp_list, x, h, alpha, test_stat_str)
}

generate_wor_sample_test <- function(n, n_trt, n_samples) {
    .Call(`_robustDESeq_generate_wor_sample_test`, n, n_trt, n_samples)
}

