# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_adaptive_permutation_test_v2 <- function(precomp_list, x, side_code, h, alpha, max_iterations, test_stat_str, custom_permutation_list) {
    .Call(`_robustDESeq_run_adaptive_permutation_test_v2`, precomp_list, x, side_code, h, alpha, max_iterations, test_stat_str, custom_permutation_list)
}

compute_score_stat_benchmark <- function(precomp, s, trt_idxs_list) {
    .Call(`_robustDESeq_compute_score_stat_benchmark`, precomp, s, trt_idxs_list)
}

run_permutation_test <- function(precomp_list, x, side_code, B, test_stat_str, custom_permutation_list) {
    .Call(`_robustDESeq_run_permutation_test`, precomp_list, x, side_code, B, test_stat_str, custom_permutation_list)
}

generate_wor_sample_test <- function(n, n_trt, n_samples) {
    .Call(`_robustDESeq_generate_wor_sample_test`, n, n_trt, n_samples)
}

compute_score_stat <- function(precomp, trt_idxs, n_trt) {
    .Call(`_robustDESeq_compute_score_stat`, precomp, trt_idxs, n_trt)
}

