# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_test_statistic <- function(a, w, D_list, trt_idxs, n_trt) {
    .Call(`_robustDESeq_compute_test_statistic`, a, w, D_list, trt_idxs, n_trt)
}

run_adaptive_permutation_test <- function(precomp_list, x, h, alpha) {
    .Call(`_robustDESeq_run_adaptive_permutation_test`, precomp_list, x, h, alpha)
}

generate_wor_sample_test <- function(n, n_trt, n_samples) {
    .Call(`_robustDESeq_generate_wor_sample_test`, n, n_trt, n_samples)
}

